// <auto-generated />
using CodeFirstCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstCrud.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220216133202_Addlogin")]
    partial class Addlogin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirstCrud.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Collegename")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(270)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Student");
                });
#pragma warning restore 612, 618
        }
    }
}
